- name: Get Pod #{{lab_pod}} instance facts
  ec2_instance_facts:
    region: '{{aws_region}}'
    filters:
      'tag:Pod': '{{lab_pod | string}}'
  register: amis

- name: Kill Pod #{{lab_pod}} EC2 Instances
  ec2:
    instance_ids: '{{ item.instance_id }}'
    state: absent
    region: '{{aws_region}}'
    wait: yes
  loop: '{{ amis.instances }}'
  register: ec2_instances
  async: 7200
  poll: 0

- name: Wait for instance termination to complete
  async_status:
    jid: '{{item.ansible_job_id}}'
  register: ec2_terminate_jobs
  until: ec2_terminate_jobs.finished
  retries: 300
  delay: 120
  loop: '{{ec2_instances.results}}'
