- include_vars:
    file: "{{vars_file_path}}"
    name: data
  register: log_data

- name: Add variables into dict
  set_fact:
    data: "{{ dict(log_data) | json_query('ansible_facts.data') }}"

- include_role:
    name: conatest_lab_helpers_auth
    public: yes
  when: access_token is undefined

- name: Guardamos las variables en la API
  uri:
    url: '{{lab_helpers_url}}/api/v1/documents/{{lab_helpers_document_id}}/'
    method: PUT
    body: '{{data}}'
    body_format: json
    headers:
      'Content-Type': 'application/json'
      'Authorization': 'Bearer {{access_token}}'
    return_content: true
  register: output

- debug:
    var: output
